"""技能枚举与 builtin 种子。prompt 正文在 llm_jobs，skills.system_prompt 列废弃。"""
from __future__ import annotations

from typing import Any

from mino_nexus.catalog.exec_classes import ALL_KINDS

ENGINES = ("agent_loop", "qa_job", "chat")
POINTERS = ("case_columns", "none")
VIEWS = ("case-three-column", "job-timeline", "flow-doc")
INPUT_TYPES = ("case", "instruction", "requirement", "none")
CATEGORIES = ("flow", "device", "channel", "sync")

ALIASES = {
    "agent-decide": "run-case",
    "agent_do": "run-case",
}

DEFAULT_SOP = {
    "phases": [
        {"id": "prep", "job": "agent-decide", "tool_kinds": ["prep", "generic", "recovery"], "guards": ["skip_repeat_read_device", "exec_script_params"], "advance_on": "signal_done"},
        {"id": "do", "job": "agent-decide", "tool_kinds": ["do", "generic", "recovery"], "guards": ["skip_repeat_tap", "limit_advise_recovery", "stuck_alternation", "block_login_after_guest"], "advance_on": "signal_done"},
        {
            "id": "check",
            "job": "agent-decide",
            "tool_kinds": ["check"],
            "guards": ["deny_mutate", "force_case_expectation"],
            "advance_on": "signal_done",
            "require": "saw_assert",
        },
    ],
    "inspections": [{"job": "inspect-session", "at": "case_start", "on_fail": "continue"}],
    "pointer": "none",
    "tool_kinds": list(ALL_KINDS),
    "max_steps": 24,
}


def _skill(
    *,
    id: str,
    label: str,
    summary: str,
    category: str,
    role_id: str,
    role_label: str,
    engine: str,
    system_prompt: str = "",
    triggers: list[str],
    sop: dict[str, Any] | None = None,
    input_spec: dict[str, Any] | None = None,
    view_id: str = "job-timeline",
    sort_order: int = 0,
) -> dict[str, Any]:
    return {
        "id": id,
        "label": label,
        "summary": summary,
        "category": category,
        "role": {"id": role_id, "label": role_label},
        "triggers": list(triggers),
        "engine": engine,
        "system_prompt": str(system_prompt or "").strip(),
        "sop": {**DEFAULT_SOP, **(sop or {})},
        "input": input_spec or {"type": "none", "map": {}},
        "view": {"id": view_id},
        "enabled": True,
        "builtin": True,
        "sort_order": sort_order,
    }


def builtin_skills() -> list[dict[str, Any]]:
    return [
        _skill(
            id="run-case",
            label="执行测试用例",
            summary="看图按前置 / 操作 / 预期推进，调用能力目录里的 function。",
            category="device",
            role_id="test-engineer",
            role_label="测试工程师",
            engine="agent_loop",
            triggers=["case_run", "instruction"],
            sop={
                "phases": DEFAULT_SOP["phases"],
                "inspections": DEFAULT_SOP["inspections"],
                "pointer": "case_columns",
                "tool_kinds": ["prep", "do", "check", "generic", "recovery"],
                "max_steps": 24,
            },
            input_spec={
                "type": "case",
                "map": {
                    "precondition": "case.precondition",
                    "steps": "case.steps",
                    "expected": "case.expected",
                },
            },
            view_id="case-three-column",
            sort_order=10,
        ),
        _skill(
            id="analyze_req",
            label="拆验收标准",
            summary="读需求原文，拆测试点和验收。",
            category="flow",
            role_id="req-analyst",
            role_label="需求分析师",
            engine="qa_job",
            triggers=["qa_tick"],
            input_spec={"type": "requirement", "map": {}},
            view_id="flow-doc",
            sort_order=20,
        ),
        _skill(
            id="draft_mindmap",
            label="写测试脑图",
            summary="按入口和端铺覆盖脑图。",
            category="flow",
            role_id="mindmap-writer",
            role_label="测试脑图编写",
            engine="qa_job",
            triggers=["qa_tick"],
            input_spec={"type": "requirement", "map": {}},
            view_id="flow-doc",
            sort_order=21,
        ),
        _skill(
            id="draft_cases",
            label="写用例草稿",
            summary="按测试点展开步骤和预期。",
            category="flow",
            role_id="case-writer",
            role_label="测试用例编写",
            engine="qa_job",
            triggers=["qa_tick"],
            input_spec={"type": "requirement", "map": {}},
            view_id="flow-doc",
            sort_order=22,
        ),
        _skill(
            id="propose_atlas",
            label="建议图谱变更",
            summary="判断需求影响哪些模块，只出品变更。",
            category="flow",
            role_id="req-analyst",
            role_label="需求分析师",
            engine="qa_job",
            triggers=["qa_tick"],
            input_spec={"type": "requirement", "map": {}},
            view_id="flow-doc",
            sort_order=23,
        ),
        _skill(
            id="conductor",
            label="分析师调度",
            summary="看当前步骤该调用哪个角色。默认走剧本。",
            category="flow",
            role_id="conductor",
            role_label="分析师",
            engine="chat",
            triggers=["qa_tick", "settings_chat"],
            view_id="job-timeline",
            sort_order=30,
        ),
        _skill(
            id="im-dialogue",
            label="IM 对话",
            summary="通道里回答测试同学并建议下一步。",
            category="channel",
            role_id="im-qa-assistant",
            role_label="IM 总指挥",
            engine="chat",
            triggers=["im_chat", "settings_chat"],
            view_id="job-timeline",
            sort_order=40,
        ),
        _skill(
            id="im-defect",
            label="IM 提缺陷",
            summary="把说清的缺陷整理成 JSON。",
            category="channel",
            role_id="im-defect-assistant",
            role_label="IM 缺陷助手",
            engine="chat",
            triggers=["im_chat", "settings_chat"],
            view_id="job-timeline",
            sort_order=41,
        ),
        _skill(
            id="req-qa-bm",
            label="需求验收",
            summary="一条需求从覆盖到验收，结论必须人审。",
            category="flow",
            role_id="req-qa-bm",
            role_label="需求QA BM",
            engine="chat",
            triggers=["settings_chat"],
            view_id="flow-doc",
            sort_order=50,
        ),
        _skill(
            id="version-qa-bm",
            label="版本发版评审",
            summary="这版带哪些需求出门、历史回归。",
            category="flow",
            role_id="version-qa-bm",
            role_label="版本QA BM",
            engine="chat",
            triggers=["settings_chat"],
            view_id="flow-doc",
            sort_order=51,
        ),
        _skill(
            id="test-engineer-chat",
            label="测试工程师（对话）",
            summary="身份说明。真机执行走「执行测试用例」。",
            category="device",
            role_id="test-engineer",
            role_label="测试工程师",
            engine="chat",
            triggers=["settings_chat"],
            view_id="job-timeline",
            sort_order=52,
        ),
        _skill(
            id="report-writer",
            label="写测试报告",
            summary="按流程事实写报告草稿。",
            category="flow",
            role_id="report-writer",
            role_label="报告编写",
            engine="chat",
            triggers=["settings_chat"],
            view_id="flow-doc",
            sort_order=60,
        ),
        _skill(
            id="doc-keeper",
            label="同步外部文档",
            summary="把人确认过的内容同步到 Wiki。",
            category="sync",
            role_id="doc-keeper",
            role_label="文档维护",
            engine="chat",
            triggers=["settings_chat"],
            view_id="flow-doc",
            sort_order=61,
        ),
        _skill(
            id="knowledge-reviewer",
            label="审核知识草稿",
            summary="审执行沉淀的知识能否注入后续匹配。",
            category="flow",
            role_id="knowledge-reviewer",
            role_label="知识审核员",
            engine="chat",
            triggers=["settings_chat"],
            view_id="job-timeline",
            sort_order=70,
        ),
        _skill(
            id="product-expert",
            label="应用简报",
            summary="提供被测应用的图谱与功能事实。",
            category="flow",
            role_id="product-expert",
            role_label="产品专家",
            engine="chat",
            triggers=["settings_chat"],
            view_id="job-timeline",
            sort_order=71,
        ),
    ]


def enums() -> dict[str, Any]:
    return {
        "engines": list(ENGINES),
        "pointers": list(POINTERS),
        "views": list(VIEWS),
        "input_types": list(INPUT_TYPES),
        "categories": list(CATEGORIES),
        "tool_kinds": list(ALL_KINDS),
    }
