"""用例密钥（ResourceClaim）词汇表：Console「用例密钥」页与编译器共用真源。"""
from __future__ import annotations

from typing import Any

CATALOG_VERSION = 7

# Claim 落库：case.meta.resource_key（v1）；与 case_scene 合并时 case_scene 优先同名字段。
CLAIM_STORAGE = {
    "primary": "case.meta.resource_key",
    "fallback_compile_from": ["precondition", "precondition_raw", "case_scene"],
    "scene_merge": "case_scene 与 resource_key 合并后 clamp_case_scene + lease_requirements",
}

LEASE_STORAGE = {
    "note": "跑批生成，勿写入用例",
    "ctx_fields": [
        "resource_lease.account_id",
        "resource_lease.project_id",
        "resource_lease.run_id",
        "resource_lease.facets",
        "picked_account",
        "sn（批次 sns[]）",
        "package_id（项目 App 包名）",
    ],
}

KEY_LAYERS = [
    {"id": "precondition", "label": "前置"},
    {"id": "operation", "label": "操作"},
    {"id": "expected", "label": "预期"},
    {"id": "generic", "label": "通用"},
]


def catalog_payload() -> dict[str, Any]:
    return {
        "version": CATALOG_VERSION,
        "claim_storage": CLAIM_STORAGE,
        "lease_storage": LEASE_STORAGE,
        "key_layers": KEY_LAYERS,
        "precondition_format": _precondition_format(),
        "prep_flow": _prep_flow(),
        "sections": _sections(),
        "entries": _entries(),
        "example_claim": _example_claim(),
        "example_precondition": _example_precondition_text(),
    }


def _precondition_format() -> dict[str, Any]:
    return {
        "lines": "编号行「类别：要求」；登录态须写清设备/账号；账号与数据用「字段名-状态」或直接写状态",
        "machine_copy": "同步写入 case.meta.resource_key 或 case_scene（推荐二者由导入/Job 生成，人工以编号前置为准）",
        "categories": [
            "设备登录态",
            "账号登录态",
            "账号与数据",
            "环境与权限",
        ],
    }


def _prep_flow() -> dict[str, Any]:
    return {
        "steps": [
            {"id": "pick_account", "label": "筛选账号", "runtime": "ensure_case_account_lease / lease_account"},
            {"id": "pick_device", "label": "筛选设备", "runtime": "批次 sns[] + device_app 机态"},
            {"id": "env_cleanup", "label": "环境清理", "runtime": "clear_app_cache 等 prep_items"},
        ],
        "removed": [
            {
                "id": "switch_run_env",
                "label": "切换测试环境",
                "note": "环境由批次 env_profile 确定，前置不再调用 check_run_env",
            }
        ],
    }


def _sections() -> list[dict[str, str]]:
    return [
        {"id": "account", "label": "账号（Claim → 号池选号）"},
        {"id": "device_app", "label": "设备 App 会话（Claim → 机态校验 / Prep）"},
        {"id": "device", "label": "设备（Claim → 派单过滤）"},
        {"id": "prep", "label": "前置动作（Claim → Prep 计划）"},
        {"id": "scene", "label": "CaseScene（Claim 子集，循环闸门）"},
        {"id": "lease", "label": "租约 Lease（运行时钥匙，勿手写）"},
    ]


def _entry(
    *,
    section: str,
    write_category: str,
    write_examples: list[str],
    claim_path: str,
    resource: str,
    config_keys: list[str],
    dsl: str,
    runtime: str,
    key_layer: str = "precondition",
    key_ref: str = "",
    expands_to: list[dict[str, Any]] | None = None,
    kind: str = "",
    block_id: str = "",
    observe: str = "",
    compile_patterns: list[dict[str, Any]] | None = None,
    schemes: list[str] | None = None,
    platforms: list[str] | None = None,
    event_name: str = "",
) -> dict[str, Any]:
    row: dict[str, Any] = {
        "section": section,
        "key_layer": key_layer,
        "write_category": write_category,
        "write_examples": write_examples,
        "claim_path": claim_path,
        "resource": resource,
        "config_keys": config_keys,
        "dsl": dsl,
        "runtime": runtime,
    }
    if key_ref:
        row["key_ref"] = key_ref
    if expands_to:
        row["expands_to"] = list(expands_to)
    if kind:
        row["kind"] = kind
    if block_id:
        row["block_id"] = block_id
    obs = str(observe or "").strip().lower()
    if obs in ("exec", "visual_each_run", "program"):
        row["observe"] = obs
    if compile_patterns:
        row["compile_patterns"] = list(compile_patterns)
    if schemes:
        row["schemes"] = list(schemes)
    if platforms:
        row["platforms"] = list(platforms)
    if event_name:
        row["event_name"] = event_name
    return row


def _entries() -> list[dict[str, Any]]:
    return [
        _entry(
            section="device_app",
            write_category="设备登录态",
            write_examples=["未登录", "游客", "已登录"],
            claim_path="device_app.required_session / case_scene.required_session",
            resource="device_app_sessions（机态登记簿）· RunContext.session_fact",
            config_keys=["session"],
            dsl="logged_out | guest | logged_in | any",
            runtime="Preflight 对照机态；不满足 → prep / inspect-session。不写进号池 session",
        ),
        _entry(
            section="account",
            write_category="账号登录态",
            write_examples=["未登录", "已登录", "游客"],
            claim_path="account.required_session / account.requirements.session",
            resource="pool_accounts + pool_account_facets.session",
            config_keys=["session"],
            dsl="session eq logged_in | session in logged_out,guest",
            runtime="仅当写了「账号登录态」才约束号池；勿映射 login_flow",
        ),
        _entry(
            section="account",
            write_category="账号与数据",
            write_examples=["形象-已配置形象", "形象-未配置形象", "个人信息配置-已配置"],
            claim_path="account.requirements.all[]",
            resource="pool_account_facets",
            config_keys=["号池模板字段 key 或中文名", "选项 value 或标签"],
            dsl="「字段名-状态」→ 该 facet eq；不扫其它字段的同名标签",
            runtime="租号时 row_satisfies_requirements",
        ),
        _entry(
            section="account",
            write_category="账号环境",
            write_examples=["测试环境", "预发环境"],
            claim_path="account.env",
            resource="pool_accounts.env",
            config_keys=["env"],
            dsl="requirements.env = test|staging|…",
            runtime="批次 env_profile 匹配同 env 账号，不是前置「切换测试环境」步骤",
            key_layer="generic",
        ),
        _entry(
            section="account",
            write_category="号池模板",
            write_examples=["模板：已注册老用户（写 template_id 或 CaseScene.account_template_id）"],
            claim_path="account.template_id / case_scene.account_template_id",
            resource="project_pool_config + 号池模板目录",
            config_keys=["template_id", "default_facets", "facet_extensions"],
            dsl="augment_requirements_with_template",
            runtime="合并模板默认约束后再选号",
            key_layer="generic",
        ),
        _entry(
            section="device_app",
            write_category="登录态（兼容旧写法）",
            write_examples=["登录态：未登录 → 视为设备登录态，不约束号池 session"],
            claim_path="device_app.required_session",
            resource="device_app_sessions",
            config_keys=["session"],
            dsl="与「设备登录态」相同",
            runtime="旧前置「登录态」只打机态，避免误检账号未登录",
        ),
        _entry(
            section="device_app",
            write_category="绑定账号",
            write_examples=["登录后绑定租约账号（默认，无需写）", "显式：绑定账号须与租约一致"],
            claim_path="device_app.binding",
            resource="device_app_sessions.bound_account_id",
            config_keys=["must_match_lease"],
            dsl="binding: must_match_lease",
            runtime="登录流完成后写 bound_account_id = lease.account_id",
            key_layer="generic",
        ),
        _entry(
            section="device",
            write_category="端",
            write_examples=["Android", "iOS", "Web"],
            claim_path="platform / case_scene.platform",
            resource="m_device.platform",
            config_keys=["android", "ios", "web", "any"],
            dsl="platform eq android",
            runtime="批跑 sns[] 过滤平台；与 Scout 通道一致",
            key_layer="generic",
        ),
        _entry(
            section="device",
            write_category="设备形态",
            write_examples=["真机 App", "Web", "App+Web"],
            claim_path="device_need / case_scene.device_need",
            resource="派单菜单（executor 集合）",
            config_keys=["app", "web", "app_web", "ab_pair"],
            dsl="device_need",
            runtime="platform_gate / 能力菜单",
            key_layer="generic",
        ),
        _entry(
            section="prep",
            write_category="环境与权限",
            write_examples=["清除应用缓存"],
            claim_path="device_app.prep[] / case_scene.prep_items",
            resource="device_app_sessions + 账号 session（清缓存联动）",
            config_keys=["kind: clear_cache"],
            dsl='prep_items: [{ "kind": "clear_cache", "phase": "before_launch" }]',
            runtime="Prep 环境清理：clear_app_cache；成功后机态 session→logged_out、绑定清除",
        ),
        _entry(
            section="prep",
            write_category="环境与权限",
            write_examples=["检查未登录", "检查已登录", "检查 App 版本"],
            claim_path="case_scene.prep_items",
            resource="device_app_sessions",
            config_keys=["check_not_logged_in", "check_logged_in", "check_app_version"],
            dsl="prep kind 见 session_gate.PREP_KINDS",
            runtime="after_launch 检查；失败则继续 prep 或拒跑",
        ),
        _entry(
            section="scene",
            write_category="前置登录策略",
            write_examples=["业务用例前置重登（隐式）", "登录模块用例勿自动登录"],
            claim_path="case_scene.session_prep",
            resource="RunContext（不持久化号池）",
            config_keys=["relogin", "logout", "skip"],
            dsl="relogin | logout | skip",
            runtime="session_ensure / 是否自动登录（跟设备登录态，不跟号池 login_flow）",
        ),
        _entry(
            section="scene",
            write_category="结构化租号",
            write_examples=["（Job 写入，一般不手写）"],
            claim_path="case_scene.lease_requirements",
            resource="pool_accounts",
            config_keys=["all", "prefer", "env"],
            dsl="与 account.requirements 同形",
            runtime="优先于纯文本编译的租号条件",
            key_layer="generic",
        ),
        _entry(
            section="operation",
            write_category="逻辑块",
            write_examples=["【块:login_email】", "登录块"],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="nav_flow_block_catalog",
            config_keys=["block_id"],
            dsl="【块:{block_id}】",
            runtime="do_program_plan kind=flow_block",
            key_layer="operation",
            key_ref="operation.block_ref",
        ),
        _entry(
            section="operation",
            write_category="登录流",
            write_examples=[
                "完成登录",
                "登录成功",
                "验证码登录",
                "邮箱验证码",
                "输入验证码并登录",
                "手机号验证码登录",
                "输入手机号或邮箱验证码",
            ],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="nav_flow_block_catalog",
            config_keys=["fb.global.login"],
            dsl="flow_block fb.global.login",
            runtime="do_program_plan kind=flow_block",
            key_layer="operation",
            key_ref="operation.login_flow",
            kind="flow_block",
            block_id="fb.global.login",
        ),
        _entry(
            section="operation",
            write_category="导航目标",
            write_examples=["【导航:screen_cart】", "进入购物车页"],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="NavFSM screen_id",
            config_keys=["nav_target"],
            dsl="【导航:{screen_id}】",
            runtime="hook fsm_navigate + nav_target",
            key_layer="operation",
            key_ref="operation.nav_target",
        ),
        _entry(
            section="operation",
            write_category="单步能力",
            write_examples=["【cap:tap_element】", "【cap:launch_app】"],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="catalog_entries",
            config_keys=["hook_cap"],
            dsl="【cap:{capability_id}】",
            runtime="do_program_plan kind=hook",
            key_layer="operation",
            key_ref="operation.cap_hook",
        ),
        _entry(
            section="operation",
            write_category="点击",
            write_examples=["点击去结算", "点击提交", "点击登录", "点按"],
            compile_patterns=[
                {
                    "priority": 20,
                    "regex": r"(?<!可)(?<!不)点击|点按",
                    "reject_if": r"不可点击|不可点|置灰",
                    "element_role": "button",
                    "event_name": "点击",
                    "hook_cap": "tap_element",
                }
            ],
            schemes=["visual", "dom"],
            event_name="点击",
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="tap_element",
            config_keys=["tap_element"],
            dsl="hook tap_element",
            runtime="agent-vision-exec 单步",
            key_layer="operation",
            key_ref="operation.tap",
        ),
        _entry(
            section="operation",
            write_category="输入",
            write_examples=["输入", "填写", "输入收货地址", "输入手机号", "输入验证码"],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="input_text",
            config_keys=["input_text"],
            dsl="hook input_text",
            runtime="agent-vision-exec 单步",
            key_layer="operation",
            key_ref="operation.input_text",
        ),
        _entry(
            section="operation",
            write_category="关闭挡屏",
            write_examples=[
                "关闭弹窗",
                "点击关闭",
                "跳过",
                "我知道了",
                "Not Now",
                "Learn More",
                "以后再说",
            ],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="tap_element / press_key",
            config_keys=["tap_element", "press_key"],
            dsl="hook tap 或返回",
            runtime="营销/权限挡屏；优先【块】或 recovery 规则",
            key_layer="operation",
            key_ref="operation.dismiss_overlay",
        ),
        _entry(
            section="operation",
            write_category="滑动",
            write_examples=["上滑", "下滑", "向左滑", "向右滑", "滑动列表"],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="swipe_direction",
            config_keys=["swipe_direction"],
            dsl="hook swipe",
            runtime="agent-vision-exec",
            key_layer="operation",
            key_ref="operation.swipe",
        ),
        _entry(
            section="operation",
            write_category="等待",
            write_examples=["等待加载", "等待页面稳定", "等待跳转"],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="wait_ms / wait_screen_ready",
            config_keys=["wait_ms"],
            dsl="hook wait",
            runtime="internal / hook",
            key_layer="operation",
            key_ref="operation.wait_ready",
            observe="program",
        ),
        _entry(
            section="operation",
            write_category="动态控件",
            write_examples=["列表第N项", "搜索结果中的一项", "动态卡片", "每次看图定位"],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="tap_element",
            config_keys=["tap_element"],
            dsl="hook tap_element observe=visual_each_run",
            runtime="每轮看图执行，不写绑定缓存",
            key_layer="operation",
            key_ref="operation.dynamic_visual",
            kind="hook",
            observe="visual_each_run",
        ),
        _entry(
            section="operation",
            write_category="购物车",
            write_examples=["打开购物车", "进入购物车"],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="Nav / 视觉",
            config_keys=["nav", "tap"],
            dsl="nav 或 visual_action",
            runtime="compound 可拆多 step",
            key_layer="operation",
            key_ref="operation.open_cart",
            expands_to=[
                {"title": "打开购物车入口", "kind": "nav", "nav_target": "screen_cart", "key_ref": "operation.open_cart.nav"},
                {"title": "确认购物车页", "kind": "visual_action", "key_ref": "operation.open_cart.confirm"},
            ],
        ),
        _entry(
            section="operation",
            write_category="勾选",
            write_examples=["勾选「{label}」", "取消勾选「{label}」"],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="tap_element",
            config_keys=["tap_element"],
            dsl="hook tap_element role=checkbox",
            runtime="点击事件，元素为勾选框，文案在 rules.label",
            key_layer="operation",
            key_ref="operation.check_box",
            kind="hook",
            event_name="勾选",
            schemes=["visual", "dom"],
            compile_patterns=[
                {
                    "priority": 60,
                    "regex": r"(?P<cancel>取消)?勾选[「『\"“](?P<label>[^」』\"”\n]+)",
                    "element_role": "checkbox",
                    "event_name": "勾选",
                    "hook_cap": "tap_element",
                    "rules_from": ["label"],
                }
            ],
        ),
        _entry(
            section="operation",
            write_category="刷新页面",
            write_examples=["刷新页面", "刷新当前页"],
            claim_path="case.meta.step_program_keys.{n}.operations[]",
            resource="reload_page",
            config_keys=["reload_page"],
            dsl="hook reload_page",
            runtime="仅 Web。看图任务也不改成点击刷新按钮",
            key_layer="operation",
            key_ref="operation.reload_page",
            kind="hook",
            event_name="刷新页面",
            platforms=["web"],
            schemes=["visual", "dom"],
            compile_patterns=[
                {
                    "priority": 60,
                    "regex": r"^(?:刷新(?:当前)?页面|刷新当前页|reload)$",
                    "event_name": "刷新页面",
                    "hook_cap": "reload_page",
                    "element_role": "page",
                }
            ],
        ),
        _entry(
            section="expected",
            write_category="文案检查",
            write_examples=["弹窗标题为「{title}」", "正文提示为「{body}」"],
            claim_path="case.meta.step_program_keys.{n}.expected[]",
            resource="agent-vision-assert / DOM 文本",
            config_keys=["assert.mode=copy"],
            dsl="ui_copy",
            runtime="身份 expected.ui_copy；标题正文只在 rules",
            key_layer="expected",
            key_ref="expected.ui_copy",
            event_name="文案检查",
            schemes=["visual", "dom"],
            compile_patterns=[
                {
                    "priority": 85,
                    "regex": r"(?:弹窗)?标题(?:为|是)\s*[「『\"“](?P<title>[^」』\"”\n]+)",
                    "element_role": "dialog",
                    "event_name": "文案检查",
                    "assert_mode": "copy",
                    "rules_from": ["title"],
                    "rules_const": {"match": "equals"},
                },
                {
                    "priority": 84,
                    "regex": r"正文(?:提示)?(?:为|是)\s*[「『\"“](?P<body>[^」』\"”\n]+)",
                    "element_role": "dialog",
                    "event_name": "文案检查",
                    "assert_mode": "copy",
                    "rules_from": ["body"],
                    "rules_const": {"match": "contains"},
                },
            ],
        ),
        _entry(
            section="expected",
            write_category="UI样式检查",
            write_examples=["按钮置灰不可点击", "按钮不可点", "按钮可点击"],
            claim_path="case.meta.step_program_keys.{n}.expected[]",
            resource="agent-vision-assert / DOM enabled",
            config_keys=["assert.mode=style"],
            dsl="ui_style",
            runtime="看图在画面上判；DOM 读 enabled。两路线不互改",
            key_layer="expected",
            key_ref="expected.ui_style",
            event_name="UI样式检查",
            schemes=["visual", "dom"],
            compile_patterns=[
                {
                    "priority": 80,
                    "regex": r"(?:(?P<label>\S{1,12})按钮)?.{0,16}(?:置灰|不可点击|不可点|禁用)",
                    "element_role": "button",
                    "event_name": "UI样式检查",
                    "assert_mode": "style",
                    "rules_from": ["label"],
                    "rules_const": {"style": "disabled"},
                },
                {
                    "priority": 78,
                    "regex": r"(?:(?P<label>\S{1,12})按钮)?.{0,8}可点击",
                    "reject_if": r"不可点击|不可点",
                    "element_role": "button",
                    "event_name": "UI样式检查",
                    "assert_mode": "style",
                    "rules_from": ["label"],
                    "rules_const": {"style": "enabled"},
                },
            ],
        ),
        _entry(
            section="expected",
            write_category="弹窗检查",
            write_examples=["{name}弹窗自动弹出", "不展示其他弹窗", "仅显示当前弹窗"],
            claim_path="case.meta.step_program_keys.{n}.expected[]",
            resource="agent-vision-assert / DOM dialog",
            config_keys=["assert.mode=dialog"],
            dsl="dialog",
            runtime="哪个弹窗与是否仅此一个在 rules；禁止拆成文案「其他」",
            key_layer="expected",
            key_ref="expected.dialog",
            event_name="弹窗检查",
            schemes=["visual", "dom"],
            compile_patterns=[
                {
                    "priority": 100,
                    "regex": r"不展示其他弹窗|没有其他弹窗|仅(?:显示|保留)?当前弹窗|只显示当前弹窗",
                    "element_role": "dialog",
                    "event_name": "弹窗检查",
                    "assert_mode": "dialog",
                    "rules_const": {"exclusive": True},
                    "merge": "dialog_exclusive",
                },
                {
                    "priority": 90,
                    "regex": r"(?P<which>.+?)弹窗(?:自动)?弹出",
                    "element_role": "dialog",
                    "event_name": "弹窗检查",
                    "assert_mode": "dialog",
                    "rules_from": ["which"],
                    "rules_const": {"present": True},
                    "merge": "dialog_present",
                },
            ],
        ),
        _entry(
            section="expected",
            write_category="输入文案检查",
            write_examples=["仅保留前{n}字符", "最多{n}字", "可输入特殊字符"],
            claim_path="case.meta.step_program_keys.{n}.expected[]",
            resource="agent-vision-assert / DOM value",
            config_keys=["assert.mode=input_value"],
            dsl="input_value",
            runtime="与同一步输入 bind；看图不读 value 属性",
            key_layer="expected",
            key_ref="expected.input_value",
            event_name="输入文案检查",
            schemes=["visual", "dom"],
            compile_patterns=[
                {
                    "priority": 75,
                    "regex": r"(?:仅保留前|最多|不超过)\s*(?P<max_length>\d+)\s*(?:个)?(?:字符|字)",
                    "element_role": "input",
                    "event_name": "输入文案检查",
                    "assert_mode": "input_value",
                    "rules_from": ["max_length"],
                    "rules_const": {"prefix_of_bound": True},
                    "needs_bind": "input_text",
                },
                {
                    "priority": 70,
                    "regex": r"(?:特殊字符|emoji|表情).{0,16}(?:均可|可正常|无报错|正常输入)|(?:均可|可)(?:正常)?输入.{0,24}(?:特殊字符|emoji|表情)",
                    "element_role": "input",
                    "event_name": "输入文案检查",
                    "assert_mode": "input_value",
                    "rules_const": {"accepts_special": True},
                    "needs_bind": "input_text",
                    "flag_if": {"无报错": {"no_error_toast": True}},
                },
            ],
        ),
        _entry(
            section="expected",
            write_category="位置关系",
            write_examples=["在{anchor}右侧有{subject}", "位于{anchor}下方"],
            claim_path="case.meta.step_program_keys.{n}.expected[]",
            resource="agent-vision-assert / DOM bounds",
            config_keys=["assert.mode=spatial"],
            dsl="spatial_relation",
            runtime="看图判方位；DOM 比 bounds。不互相补刀",
            key_layer="expected",
            key_ref="expected.spatial_relation",
            event_name="位置关系观察",
            schemes=["visual", "dom"],
            compile_patterns=[
                {
                    "priority": 65,
                    "regex": r"在(?P<relative_to>.+?)的?(?P<relation_zh>右侧|左边|左侧|上方|下方|右边)(?:有|出现)(?P<subject>.+)",
                    "element_role": "overlay",
                    "event_name": "位置关系观察",
                    "assert_mode": "spatial",
                    "rules_from": ["relative_to", "subject", "relation_zh"],
                }
            ],
        ),
        _entry(
            section="expected",
            write_category="文案",
            write_examples=["文案包含", "页面包含"],
            claim_path="case.meta.step_program_keys.{n}.expected[]",
            resource="agent-vision-assert",
            config_keys=["assert.mode=vlm"],
            dsl="ui_text",
            runtime="check_program_plan checkpoint",
            key_layer="expected",
            key_ref="expected.ui_text",
        ),
        _entry(
            section="expected",
            write_category="登录态",
            write_examples=["session=logged_in", "已登录", "未登录", "游客态"],
            claim_path="case.meta.step_program_keys.{n}.expected[]",
            resource="inspect-session",
            config_keys=["assert.mode=session"],
            dsl="session=",
            runtime="checkpoint + inspect",
            key_layer="expected",
            key_ref="expected.session_state",
            observe="program",
        ),
        _entry(
            section="expected",
            write_category="导航",
            write_examples=["当前屏", "进入", "跳转", "详情页"],
            claim_path="case.meta.step_program_keys.{n}.expected[]",
            resource="Nav 定位",
            config_keys=["screen_id"],
            dsl="navigation checkpoint",
            runtime="check_program_plan",
            key_layer="expected",
            key_ref="expected.screen_reached",
        ),
        _entry(
            section="expected",
            write_category="不应出现",
            write_examples=["不应出现", "不包含", "没有", "未展示"],
            claim_path="case.meta.step_program_keys.{n}.expected[]",
            resource="agent-vision-assert",
            config_keys=["assert.mode=vlm"],
            dsl="ui_absent",
            runtime="checkpoint negation",
            key_layer="expected",
            key_ref="expected.ui_absent",
        ),
        _entry(
            section="expected",
            write_category="数量",
            write_examples=["数量为", "数量为 1", "角标"],
            claim_path="case.meta.step_program_keys.{n}.expected[]",
            resource="VLM assert",
            config_keys=["counter"],
            dsl="counter",
            runtime="checkpoint vlm",
            key_layer="expected",
            key_ref="expected.counter",
        ),
        _entry(
            section="lease",
            write_category="—",
            write_examples=["（跑批时 Nexus 写入，用例不写）"],
            claim_path="RunContext.resource_lease",
            resource="pool_accounts.lease + run_id",
            config_keys=["account_id", "run_id", "expires_at", "facets"],
            dsl="—",
            runtime="case 结束 / 取消 → release_run_lease",
            key_layer="generic",
        ),
        _entry(
            section="lease",
            write_category="—",
            write_examples=["（跑批参数 sns[] + 项目 App 包名）"],
            claim_path="批次 run + ctx.sn",
            resource="m_device + device_app_sessions",
            config_keys=["sn", "package_id", "node_id"],
            dsl="—",
            runtime="EXECUTE 路由；状态转移带 run_id 鉴权",
            key_layer="generic",
        ),
    ]


def _example_precondition_text() -> str:
    return (
        "1. 设备登录态：未登录\n"
        "2. 账号与数据：形象-已配置形象\n"
        "3. 环境与权限：清除应用缓存"
    )


def _example_claim() -> dict[str, Any]:
    return {
        "version": CATALOG_VERSION,
        "platform": "android",
        "device_need": "app",
        "target_app": {"app_id": "<项目内应用 ID>", "package": "<包名，派单解析>"},
        "device_app": {
            "required_session": "logged_out",
            "allow": ["logged_out", "guest"],
            "prep": [{"kind": "clear_cache", "phase": "before_launch", "text": "清除应用缓存"}],
            "binding": "must_match_lease",
        },
        "account": {
            "env": "test",
            "required_session": "any",
            "template_id": "",
            "requirements": {
                "all": [
                    {"facet": "field_7065t5", "op": "eq", "value": "yes"},
                    {"facet": "health", "op": "eq", "value": "available"},
                ],
                "prefer": [],
                "env": "test",
            },
        },
        "case_scene": {
            "required_session": "guest",
            "session_prep": "logout",
            "platform": "android",
            "device_need": "app",
            "prep_items": [
                {"kind": "clear_cache", "phase": "before_launch", "text": "清除应用缓存"},
            ],
        },
    }
